### PR TITLE
:tada:  add reaction roles

### PR DESCRIPTION
**Pull request by tovade**
This pull request includes:
Reaction roles ;=)

### CODE REVIEW

**Comment by Spiderjockey02** [comment]
I will have a proper look into this very good pull request this weekend (just working on a few bugs before anything new)

**Comment by tovade** [comment]
👍 let me know when i need to merge the bug fixes

**Comment by tovade** [comment]
If you need to contact me on discord tovade#6617

**Comment by tovade** [comment]
im also in listcord (thats how i found this awesome bot)

**Pull request merged**
