### PR TITLE
Update inviteCreate.js

### PR DESCRIPTION
**Pull request by LLouisplayz**

### CODE REVIEW

**Comment by LLouisplayz** [comment]
from
.setAuthor({name: 'Invite created:', iconURL: invite.inviter.displayAvatarURL(}))

to
.setAuthor({ name: 'Invite created:', iconURL: invite.inviter.displayAvatarURL });

**Comment by LLouisplayz** [comment]
can you delete this plz

**Comment by Spiderjockey02** [comment]
I can't delete only close/open

**Comment by LLouisplayz** [comment]
ah okey so you can only delete issues

i understand

**Pull request closed without merging**
