### PR TITLE
Magmastream

### PR DESCRIPTION
**Pull request by thororen1234**
instead of erela.js which has been discontinued from the looks of it I moved the audio/music player to magmastream, upgraded lavalink so it would work with magmastream added the spotify plugin for lavalink so it uses lavalink instead of the bot, and added back 247 also add back the radio file that was in assets or delete radio lol it won't work now.

### CODE REVIEW

**Comment by Spiderjockey02** [comment]
LGTM for now. The radio command is indeed bugged, it should be fetching from my API not a non-existent JSON file, so I'll fix that now.

**Comment by thororen1234** [comment]
Okay once that's done I'll readd radio

**Comment by Spiderjockey02** [comment]
yep radio cmd is now fixed so u can resolve the conflict

**Comment by thororen1234** [comment]
Alright I added it back

**Comment by thororen1234** [comment]
Heads up I made it discordjs v14.12. Whatever comes after that I forgot and got effects you have to use the reset function Im leaving it up to you to see if you can fix that.

**Comment by birongliu** [comment]
Eh...

**Comment by Spiderjockey02** [comment]
Just had a look at lavasrc, I don't see why everything shouldn't be enabled by default?

**Comment by Spiderjockey02** [comment]
Just had a look at lavasrc, I don't see why everything shouldn't be enabled by default?

**Comment by birongliu** [comment]
I think we should let those people who clone the repository decide what to enable (but for egglord can enable everything?)

**Comment by thororen1234** [comment]
That was my bad I just copied my config I'll fix it

**Pull request merged**
