### PR TITLE
Fixed the playlist cmd

### PR DESCRIPTION
**Pull request by thororen1234**
self explanatory for the title
I did however modify all the lang files to no longer have the title of the playlist or whatever to the it was for the name spot

### CODE REVIEW

**Comment by thororen1234** [comment]
I'm not going to lie ben I'm gonna leave the thumbnail fixing to you as I tried for a bit and couldn't get it to work for the playlists so I removed it as a whole

**Comment by Spiderjockey02** [comment]
lol that's fine; does this fix all the playlist commands to work as expected?

**Comment by thororen1234** [comment]
from what I can tell yes

**Comment by thororen1234** [comment]
it loaded my spotify playlist and successfully viewed it loaded it and such

**Pull request merged**
